### ISSUE TITLE
不兼容5.0以下版本  共享元素转场动画Crash

### ISSUE THREAD

**Issue by bobSir** [razerdp/FriendCircle#47]

**Comment by razerdp** [comment]
crash信息有吗

另外，我似乎并没有用共享元素转场

**Comment by bobSir** [comment]
03-27 18:06:58.231 30505-30505/razerdp.friendcircle E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: razerdp.friendcircle, PID: 30505
                                                                      java.lang.RuntimeException: Unable to stop activity {razerdp.friendcircle/razerdp.friendcircle.activity.gallery.PhotoBrowseActivity}: java.lang.SecurityException: Permission Denial: getTasks() from pid=30505, uid=10150 requires android.permission.GET_TASKS
                                                                          at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3475)
                                                                          at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3529)
                                                                          at android.app.ActivityThread.access$1400(ActivityThread.java:138)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1252)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5061)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:812)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: java.lang.SecurityException: Permission Denial: getTasks() from pid=30505, uid=10150 requires android.permission.GET_TASKS
                                                                          at android.os.Parcel.readException(Parcel.java:1465)
                                                                          at android.os.Parcel.readException(Parcel.java:1419)
                                                                          at android.app.ActivityManagerProxy.getTasks(ActivityManagerNative.java:2596)
                                                                          at android.app.ActivityManager.getRunningTasks(ActivityManager.java:774)
                                                                          at android.app.ActivityManager.getRunningTasks(ActivityManager.java:810)
                                                                          at razerdp.github.com.baselibrary.base.BaseActivity.isApplicationInBackground(BaseActivity.java:66)
                                                                          at razerdp.github.com.baselibrary.base.BaseActivity.onStop(BaseActivity.java:36)
                                                                          at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1215)
                                                                          at android.app.Activity.performStop(Activity.java:5387)
                                                                          at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3470)
                                                                          at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3529) 
                                                                          at android.app.ActivityThread.access$1400(ActivityThread.java:138) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1252) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5061) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:812) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) 
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by bobSir** [comment]
看样子 好像并不是 转场动画引发的Crash

**Comment by razerdp** [comment]
我明白了，应该是组件化重构后我对BaseActivity再次做了个优化，加了一个判断App是否在前台的方法，那个方法触发了securityException

**Comment by bobSir** [comment]
行 了解了  我只是过来学习一下转场动画的 我先看源码了  谢谢啊

**Comment by razerdp** [comment]
好的，imageview的转场在baseuilib/widget/imageview/GalleryPhotoView下

对应的是 playEnterAnima和playExitAnima

退出归位动画实现是通过操作bitmap的matrix使之缩放并移动到外面小View位置的。

希望能够帮到你，如果有更好的想法欢迎提交pr哦
