### ISSUE TITLE
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@70e62c7

### ISSUE THREAD

**Issue by bobSir** [razerdp/FriendCircle#52]
at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1271)
                                                                            at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:257)
                                                                            at android.graphics.Canvas.drawBitmap(Canvas.java:1415)
                                                                            at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
                                                                            at android.widget.ImageView.onDraw(ImageView.java:1286)
                                                                            at android.view.View.draw(View.java:17134)
                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16116)
                                                                            at android.view.View.draw(View.java:16900)
                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                            at org.apmem.tools.layouts.FlowLayout.drawChild(FlowLayout.java:359)
                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)

**Comment by bobSir** [comment]
报了一个FlowLayout一个Crash。
项目中是用Fresco图片加载框架，在用Fresco下载图片以后 拿到Bitmap设置给imageview。
如果图片加载框架是Fresco，应该怎么做票圈里面的转场动画，求指教。。

**Comment by razerdp** [comment]
这个crash信息不够详细诶，虽然是指向于flowlayout，但其实是flowlayout的drawchild，所以其实还是自定义控件的问题，建议断点看看PhotoContents的onMeasure方法。

**Comment by bobSir** [comment]
问题是出在用fresco下载图片 得到bitmap 设置给ImageView， 我采用其他的图片加载框架 是没有问题的，但用的是Fresco。UP有何高见

**Comment by razerdp** [comment]
下载的bitmap，然后设置么，，，你看看crash信息有没有类似于“System.err: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap ”的字样。

**Comment by bobSir** [comment]
对Crash日志就是这个“System.err: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap ”

 dataSource.subscribe  这个方法下载图片成功后 有个回调 参数里有Bitmap 。 直接设置给ImageView，

**Comment by razerdp** [comment]
一般来说，使用bitmap请判断一下bitmap.isRecycled()

**Comment by razerdp** [comment]
事实上没记错fresco使用ashmen内存，对于bitmap都是在C层自行调配（显性释放）的，在fresco的git上有一个类似的issue，或者你也可以搜搜其他类似的[#648](https://github.com/facebook/fresco/issues/648)
