### ISSUE TITLE
6.0会有权限问题，扫描SD卡要动态申请权限，请修复这个bug

### ISSUE THREAD

**Issue by cbuemc** [razerdp/FriendCircle#56]
6.0会有权限问题，扫描SD卡要动态申请权限，请修复这个bug
java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=28318, uid=10080 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                                          at android.os.Parcel.readException(Parcel.java:1620)
                                                                          at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                          at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                          at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
                                                                          at android.content.ContentResolver.query(ContentResolver.java:491)
                                                                          at android.content.ContentResolver.query(ContentResolver.java:434)
                                                                          at razerdp.github.com.baselibrary.manager.localphoto.LocalPhotoManager.scanImg(LocalPhotoManager.java:110)
                                                                          at razerdp.github.com.baselibrary.manager.localphoto.LocalPhotoManager$1.run(LocalPhotoManager.java:76)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)

**Comment by cbuemc** [comment]
java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=28318, uid=10080 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                                          at android.os.Parcel.readException(Parcel.java:1620)
                                                                          at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                          at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                          at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
                                                                          at android.content.ContentResolver.query(ContentResolver.java:491)
                                                                          at android.content.ContentResolver.query(ContentResolver.java:434)
                                                                          at razerdp.github.com.baselibrary.manager.localphoto.LocalPhotoManager.scanImg(LocalPhotoManager.java:110)
                                                                          at razerdp.github.com.baselibrary.manager.localphoto.LocalPhotoManager$1.run(LocalPhotoManager.java:76)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)

**Comment by razerdp** [comment]
@cbuemc
你好，，暂时来说我还没针对6.0以上的适配。。。其实都是权限的问题，这个需要迟点再完成

**Comment by razerdp** [comment]
@cbuemc 你好，已经增加适配了。请pull一下代码

**Comment by cbuemc** [comment]
好的，非常感谢

**Comment by razerdp** [comment]
@cbuemc master分支。。。main-dev没有push
