### ISSUE TITLE
预览手机相册图片崩溃

### ISSUE THREAD

**Issue by hy20160705** [razerdp/FriendCircle#81]
api-26 

018-11-13 16:52:55.053 28859-28859/razerdp.friendcircle E/AndroidRuntime: FATAL EXCEPTION: main
    Process: razerdp.friendcircle, PID: 28859
    java.lang.RuntimeException: Unable to start activity ComponentInfo{razerdp.friendcircle/razerdp.github.com.photoselect.PhotoMultiBrowserActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
        at android.app.Activity.onCreate(Activity.java:1038)
        at android.support.v4.app.SupportActivity.onCreate(SupportActivity.java:66)
        at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:321)
        at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
        at razerdp.github.com.lib.base.BaseActivity.onCreate(BaseActivity.java:39)
        at razerdp.github.com.photoselect.PhotoMultiBrowserActivity.onCreate(PhotoMultiBrowserActivity.java:73)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)

**Comment by razerdp** [comment]
你好，是否最新的代码？最新代码已经适配了这个问题

**Comment by yjandroid** [comment]
我也是
闪退，最新的代码

**Comment by razerdp** [comment]
fixed
